#!/usr/bin/env node
// Model catalog — upstream autodetection + the ONE long-context rule.
//
// Guards the two operator-directed invariants (2026-06-10):
//  1. /v1/models is autodetected from upstream with a baked fallback that
//     can never fail closed.
//  2. Every family gets its [1m] long-context variant by the same rule
//     (haiku excluded), and `<family>1m` aliases DERIVE from `<family>` —
//     the opus/opus1m version drift (#389) can't reoccur.

import assert from 'node:assert';
import {
  BAKED_BASE_MODELS,
  longContextEligible,
  withLongContextVariants,
  modelVersionKey,
  normalizeUpstreamIds,
  resolveFamilyBase,
  resolveAliasAgainst,
  buildOpenAIModelsList,
  getModelCatalog,
  getCachedBases,
  retryModelCatalogNow,
  _resetModelCatalogForTest,
  DEFAULT_CATALOG_TTL_MS,
  suspendedFamilies,
  isSuspendedModel,
  dropSuspendedModels,
} from '../dist/model-catalog.js';
import { OPENAI_MODELS_LIST, resolveClaudeAlias } from '../dist/proxy.js';

let passed = 0;
function check(name, cond) {
  assert.ok(cond, name);
  passed++;
}

// ---------------------------------------------------------------------------
console.log('  long-context rule — one rule, every family');

check('fable is eligible', longContextEligible('claude-fable-5'));
check('opus is eligible', longContextEligible('claude-opus-4-8'));
check('sonnet is eligible', longContextEligible('claude-sonnet-4-6'));
check('haiku is NOT eligible', !longContextEligible('claude-haiku-4-5'));
check('already-tagged id is not eligible', !longContextEligible('claude-fable-5[1m]'));
check('non-claude id is not eligible', !longContextEligible('gpt-4o'));
check('a dated future model is eligible', longContextEligible('claude-opus-4-9-20270101'));

const expanded = withLongContextVariants(BAKED_BASE_MODELS);
for (const base of BAKED_BASE_MODELS) {
  const i = expanded.indexOf(base);
  check(`expanded list contains ${base}`, i !== -1);
  if (longContextEligible(base)) {
    check(`${base}[1m] immediately follows its base`, expanded[i + 1] === `${base}[1m]`);
  } else {
    check(`${base} has no [1m] variant`, !expanded.includes(`${base}[1m]`));
  }
}

// The exported baked /v1/models payload is generated by the same rule —
// opus/sonnet [1m] variants are now advertised exactly like fable's.
const listedIds = OPENAI_MODELS_LIST.data.map((m) => m.id);
check('baked listing advertises claude-opus-4-8[1m]', listedIds.includes('claude-opus-4-8[1m]'));
check('baked listing advertises claude-sonnet-4-6[1m]', listedIds.includes('claude-sonnet-4-6[1m]'));
check('baked listing advertises claude-fable-5[1m]', listedIds.includes('claude-fable-5[1m]'));
check('baked listing has NO haiku [1m]', !listedIds.includes('claude-haiku-4-5[1m]'));
check('baked listing matches the generated expansion exactly',
  JSON.stringify(listedIds) === JSON.stringify(expanded));

// ---------------------------------------------------------------------------
console.log('  upstream id normalization');

const upstreamSample = [
  'claude-opus-4-8',            // newest-first upstream order
  'claude-fable-5-20260601',    // dated dupe of a short id later in the list
  'claude-fable-5',
  'claude-opus-4-7',
  'claude-sonnet-4-6-20251101', // dated-only — kept as-is
  'claude-haiku-4-5',
  'claude-3-5-sonnet-20241022', // legacy generation — dropped
  'claude-3-haiku-20240307',    // legacy generation — dropped
  'gpt-4o',                     // not ours — dropped
  'claude-zenith-6',            // unknown future family — kept, ranked last
];
const normalized = normalizeUpstreamIds(upstreamSample);
check('short id wins over its dated duplicate',
  normalized.includes('claude-fable-5') && !normalized.includes('claude-fable-5-20260601'));
check('dated-only id is kept', normalized.includes('claude-sonnet-4-6-20251101'));
check('legacy claude-3-x generations are dropped',
  !normalized.some((id) => id.startsWith('claude-3-')));
check('non-claude ids are dropped', !normalized.includes('gpt-4o'));
check('unknown future family is kept (autodetection point)', normalized.includes('claude-zenith-6'));
check('unknown family ranks last', normalized[normalized.length - 1] === 'claude-zenith-6');
check('fable ranks first', normalized[0] === 'claude-fable-5');
check('opus versions ordered desc',
  normalized.indexOf('claude-opus-4-8') < normalized.indexOf('claude-opus-4-7'));

// ---------------------------------------------------------------------------
console.log('  family resolution + alias derivation');

check('version key parses', JSON.stringify(modelVersionKey('claude-opus-4-8')) === '[4,8]');
check('newest opus wins', resolveFamilyBase('opus', BAKED_BASE_MODELS) === 'claude-opus-4-8');
check('a future opus auto-bumps the alias',
  resolveFamilyBase('opus', ['claude-opus-4-8', 'claude-opus-4-9']) === 'claude-opus-4-9');
check('absent family resolves null', resolveFamilyBase('opus', ['claude-haiku-4-5']) === null);

check("'opus' resolves", resolveAliasAgainst('opus', BAKED_BASE_MODELS) === 'claude-opus-4-8');
check("'opus1m' DERIVES from 'opus' — same base + [1m]",
  resolveAliasAgainst('opus1m', BAKED_BASE_MODELS) === 'claude-opus-4-8[1m]');
check("'fable1m' derives the same way",
  resolveAliasAgainst('fable1m', BAKED_BASE_MODELS) === 'claude-fable-5[1m]');
check("'sonnet1m' derives the same way",
  resolveAliasAgainst('sonnet1m', BAKED_BASE_MODELS) === 'claude-sonnet-5[1m]');
check("'haiku1m' is refused by the rule", resolveAliasAgainst('haiku1m', BAKED_BASE_MODELS) === null);
check('full ids are not alias-resolved', resolveAliasAgainst('claude-opus-4-8', BAKED_BASE_MODELS) === null);
check('unknown shorthand is not alias-resolved', resolveAliasAgainst('zenith', BAKED_BASE_MODELS) === null);

// proxy-level resolution: dynamic rule first, legacy pins intact
check("proxy resolveClaudeAlias('opus1m') agrees with the derivation",
  resolveClaudeAlias('opus1m') === 'claude-opus-4-8[1m]');
check("legacy pin 'opus47' still resolves statically",
  resolveClaudeAlias('opus47') === 'claude-opus-4-7');

// ---------------------------------------------------------------------------
console.log('  catalog cache — fetch, fallback, TTL, backoff');

function fakeFetch(ids, calls) {
  return async () => {
    calls.count++;
    return {
      ok: true,
      status: 200,
      json: async () => ({ data: ids.map((id) => ({ id })) }),
    };
  };
}
const token = async () => 'test-token';

// success path
_resetModelCatalogForTest();
{
  const calls = { count: 0 };
  let t = 1_000_000;
  const deps = { fetchImpl: fakeFetch(['claude-opus-4-8', 'claude-haiku-4-5'], calls), getToken: token, now: () => t };
  const cat = await getModelCatalog(deps);
  check('successful fetch → source upstream', cat.source === 'upstream');
  check('successful fetch → normalized bases', JSON.stringify(cat.bases) === JSON.stringify(['claude-opus-4-8', 'claude-haiku-4-5']));
  check('cached bases visible synchronously', getCachedBases().includes('claude-opus-4-8'));
  await getModelCatalog(deps);
  check('within TTL → no second fetch', calls.count === 1);
  t += DEFAULT_CATALOG_TTL_MS + 1;
  const stale = await getModelCatalog(deps);
  check('past TTL → stale served immediately (revalidate is async)', stale.source === 'upstream');
  await new Promise((r) => setImmediate(r));
  check('background revalidate fired', calls.count === 2);
}

// failure path — baked fallback + retry backoff
_resetModelCatalogForTest();
{
  let attempts = 0;
  let t = 2_000_000;
  const failingDeps = {
    fetchImpl: async () => { attempts++; throw new Error('offline'); },
    getToken: token,
    now: () => t,
  };
  const cat = await getModelCatalog(failingDeps);
  check('fetch failure → baked fallback', cat.source === 'baked');
  check('baked fallback serves the baked set minus suspended families', JSON.stringify(cat.bases) === JSON.stringify(dropSuspendedModels(BAKED_BASE_MODELS)));
  await getModelCatalog(failingDeps);
  await new Promise((r) => setImmediate(r));
  check('failures back off (no hammering within retry window)', attempts === 1);
}

// retryModelCatalogNow — bypasses the failed-fetch backoff when auth just
// became available (first admin hot-add, #636)
_resetModelCatalogForTest();
{
  const t = 5_000_000;
  let failedAttempts = 0;
  const noAccountsDeps = {
    fetchImpl: async () => { failedAttempts++; throw new Error('pool has no accounts yet'); },
    getToken: token,
    now: () => t,
  };
  const cold = await getModelCatalog(noAccountsDeps);
  check('no-accounts fetch failure → baked', cold.source === 'baked');

  // Account hot-added moments later: a plain getModelCatalog is still inside
  // the 5-min retry backoff and must NOT attempt upstream…
  const calls = { count: 0 };
  const workingDeps = { fetchImpl: fakeFetch(['claude-opus-4-8'], calls), getToken: token, now: () => t + 1_000 };
  const stillBaked = await getModelCatalog(workingDeps);
  await new Promise((r) => setImmediate(r));
  check('within retry backoff → no upstream attempt', calls.count === 0 && stillBaked.source === 'baked');

  // …but retryModelCatalogNow resets the backoff and refetches immediately.
  retryModelCatalogNow(workingDeps);
  await new Promise((r) => setTimeout(r, 10));
  check('retryModelCatalogNow bypasses the backoff', calls.count === 1);
  check('catalog upgraded from baked to upstream', (await getModelCatalog(workingDeps)).source === 'upstream');
}

// non-200 and empty responses also fall back
_resetModelCatalogForTest();
{
  const deps401 = { fetchImpl: async () => ({ ok: false, status: 401, json: async () => ({}) }), getToken: token, now: () => 3_000_000 };
  const cat = await getModelCatalog(deps401);
  check('upstream 401 → baked fallback', cat.source === 'baked');
}
_resetModelCatalogForTest();
{
  const calls = { count: 0 };
  const depsEmpty = { fetchImpl: fakeFetch(['gpt-4o'], calls), getToken: token, now: () => 4_000_000 };
  const cat = await getModelCatalog(depsEmpty);
  check('no usable claude ids → baked fallback', cat.source === 'baked');
}

// x-api-key mode sends the key, not a bearer
_resetModelCatalogForTest();
{
  let seenHeaders = null;
  const deps = {
    fetchImpl: async (_url, opts) => {
      seenHeaders = opts.headers;
      return { ok: true, status: 200, json: async () => ({ data: [{ id: 'claude-opus-4-8' }] }) };
    },
    upstreamApiKey: 'sk-test',
    now: () => 5_000_000,
  };
  await getModelCatalog(deps);
  check('upstreamApiKey mode → x-api-key header', seenHeaders['x-api-key'] === 'sk-test');
  check('upstreamApiKey mode → no bearer', seenHeaders['authorization'] === undefined);
}

// buildOpenAIModelsList shape
const shape = buildOpenAIModelsList(['claude-fable-5']);
check('OpenAI list shape', shape.object === 'list' && shape.data[0].id === 'claude-fable-5'
  && shape.data[0].object === 'model' && shape.data[0].owned_by === 'anthropic');

// ---------------------------------------------------------------------------
console.log('  suspended models — none by default (Fable 5 returned globally 2026-07-01); env mechanism intact');
{
  const ORIG = process.env.DARIO_SUSPENDED_MODELS;

  // Default (env unset): NOTHING is suspended. The 2026-06-12 US-gov directive
  // that had dario defaulting to a `fable` suspension was lifted and Fable 5
  // returned globally on 2026-07-01, so the default set is now empty.
  delete process.env.DARIO_SUSPENDED_MODELS;
  check('default: fable NOT suspended', !isSuspendedModel('claude-fable-5'));
  check('default: fable[1m] NOT suspended', !isSuspendedModel('claude-fable-5[1m]'));
  check('default: bare `fable` alias NOT suspended', !isSuspendedModel('fable'));
  check('default: `claude:fable` prefix NOT suspended', !isSuspendedModel('claude:fable'));
  check('default: opus NOT suspended', !isSuspendedModel('claude-opus-4-8'));
  check('default: sonnet NOT suspended', !isSuspendedModel('claude-sonnet-4-6'));
  check('default: haiku NOT suspended', !isSuspendedModel('claude-haiku-4-5'));
  check('default: suspendedFamilies empty', suspendedFamilies().size === 0);

  // dropSuspendedModels is a no-op by default — fable stays in the list.
  const kept = dropSuspendedModels(['claude-fable-5', 'claude-opus-4-8', 'claude-sonnet-4-6']);
  check('default: dropSuspendedModels keeps fable', kept.includes('claude-fable-5'));
  check('default: dropSuspendedModels keeps all, in order',
    kept.length === 3 && kept[0] === 'claude-fable-5' && kept[2] === 'claude-sonnet-4-6');

  // Catalog advertises fable again (upstream + baked fallback).
  _resetModelCatalogForTest();
  {
    const cat = await getModelCatalog({
      fetchImpl: async () => ({ ok: true, status: 200,
        json: async () => ({ data: [{ id: 'claude-fable-5' }, { id: 'claude-opus-4-8' }] }) }),
      getToken: async () => 'tok', now: () => 6_000_000,
    });
    check('default: upstream catalog advertises fable', cat.bases.includes('claude-fable-5'));
    check('default: getCachedBases includes fable', getCachedBases().includes('claude-fable-5'));
  }
  _resetModelCatalogForTest();
  {
    const cat = await getModelCatalog({
      fetchImpl: async () => { throw new Error('offline'); },
      getToken: async () => 'tok', now: () => 7_000_000,
    });
    check('default: baked fallback includes fable', cat.source === 'baked' && cat.bases.includes('claude-fable-5'));
  }

  // The mechanism still works: explicitly suspending `fable` (e.g. if access is
  // ever pulled again) drops it in every spelling and everywhere it's listed.
  process.env.DARIO_SUSPENDED_MODELS = 'fable';
  check('=fable: fable id suspended', isSuspendedModel('claude-fable-5'));
  check('=fable: fable[1m] suspended', isSuspendedModel('claude-fable-5[1m]'));
  check('=fable: bare `fable` alias suspended', isSuspendedModel('fable'));
  check('=fable: `fable1m` alias suspended', isSuspendedModel('fable1m'));
  check('=fable: `claude:fable` prefix suspended', isSuspendedModel('claude:fable'));
  check('=fable: opus NOT suspended', !isSuspendedModel('claude-opus-4-8'));
  check('=fable: suspendedFamilies = {fable}',
    suspendedFamilies().size === 1 && suspendedFamilies().has('fable'));
  const dropped = dropSuspendedModels(['claude-fable-5', 'claude-opus-4-8', 'claude-sonnet-4-6']);
  check('=fable: dropSuspendedModels removes fable', !dropped.includes('claude-fable-5'));
  check('=fable: dropSuspendedModels keeps the rest in order',
    dropped.length === 2 && dropped[0] === 'claude-opus-4-8' && dropped[1] === 'claude-sonnet-4-6');
  _resetModelCatalogForTest();
  {
    const cat = await getModelCatalog({
      fetchImpl: async () => ({ ok: true, status: 200,
        json: async () => ({ data: [{ id: 'claude-fable-5' }, { id: 'claude-opus-4-8' }] }) }),
      getToken: async () => 'tok', now: () => 7_500_000,
    });
    check('=fable: upstream catalog drops fable despite upstream listing it',
      cat.source === 'upstream' && !cat.bases.includes('claude-fable-5'));
    check('=fable: getCachedBases excludes fable', !getCachedBases().includes('claude-fable-5'));
  }

  // Override path: suspend a different family, by id or by name (both → family).
  process.env.DARIO_SUSPENDED_MODELS = 'claude-opus-4-8, sonnet';
  check('override: opus suspended (id → family)', isSuspendedModel('claude-opus-4-8'));
  check('override: sonnet suspended (name → family)', isSuspendedModel('claude-sonnet-4-6'));
  check('override: fable NOT suspended', !isSuspendedModel('claude-fable-5'));
  check('override: families = {opus, sonnet}',
    suspendedFamilies().size === 2 && suspendedFamilies().has('opus') && suspendedFamilies().has('sonnet'));

  if (ORIG === undefined) delete process.env.DARIO_SUSPENDED_MODELS;
  else process.env.DARIO_SUSPENDED_MODELS = ORIG;
}

// #8 (#642-audit): a hung getToken() must NOT wedge the catalog. The fetch
// timeout now bounds token acquisition too, so getModelCatalog falls back to
// the baked list instead of hanging on a never-resolving refresh.
_resetModelCatalogForTest();
{
  let t = 9_000_000;
  const neverToken = () => new Promise(() => {}); // never resolves
  const deps = { getToken: neverToken, timeoutMs: 50, now: () => t };
  const cat = await getModelCatalog(deps);
  check('hung getToken → baked fallback (no hang)', cat.source === 'baked');
  t += 6 * 60 * 1000; // past the retry backoff
  const cat2 = await getModelCatalog(deps);
  check('not wedged — second call still returns', cat2.source === 'baked');
}

// suspendedFamilies memoization (#642-audit): same env value returns the cached
// Set (no per-call rebuild); a changed env value re-parses.
{
  const ORIG = process.env.DARIO_SUSPENDED_MODELS;
  process.env.DARIO_SUSPENDED_MODELS = 'fable';
  const a = suspendedFamilies();
  const b = suspendedFamilies();
  check('same env value → same Set reference (memoized)', a === b);
  process.env.DARIO_SUSPENDED_MODELS = 'opus';
  const cSet = suspendedFamilies();
  check('changed env value → re-parsed (new Set)', cSet !== a && cSet.has('opus'));
  process.env.DARIO_SUSPENDED_MODELS = '';
  check('cleared env → empty set', suspendedFamilies().size === 0);
  if (ORIG === undefined) delete process.env.DARIO_SUSPENDED_MODELS;
  else process.env.DARIO_SUSPENDED_MODELS = ORIG;
}

_resetModelCatalogForTest();
console.log(`✅ model-catalog: ${passed} assertions passed`);
